name: Auto Thank Contributors

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-thank:
    runs-on: ubuntu-latest
    steps:
      - name: Post Thank You Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number || github.event.pull_request.number }}
          body: |
            Hi @${{ github.actor }} ğŸ‘‹
            
            ğŸ™ Thank you for creating this issue/PR!  
            The repo owner or mentor will review it soon.
            Meanwhile, you can check out the [contribution guidelines](https://github.com/UjjwalSaini07/Bharat-Bhakti-Yatra?tab=contributing-ov-file)